config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
    end

    def new
        @flat = Flat.new
    end

    def show
        @flat = Flat.find(params[:id])
    end

    def create
        @flat = Flat.new(flat_params)
        if @flat.save
            redirect_to flat_path(@flat)
        else
            render :new
        end
    end

    def edit
        @flat = Flat.find(params[:id])
        redirect_to flat_path(@flat)
    end

    def destroy
        @flat = Flat.find(params[:id])
        @flat.destroy
        redirect_to flats_path
    end

    

    private
    def flat_params
        params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end


# TODO: ADD VALIDATIONS, CREATE SHOW/EDIT HTML & CSS, FIND RANDOM IMGURL GENERATOR GEM, SEARCH FUNCTION

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline ml-auto">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    <button class="btn btn-outline-primary my-2 my-sm-0 ml-2"><%= link_to 'Add Flat', new_flat_path%></button>
  </form>
</nav>




<h1 class="d-flex justify-content-center"><%= "All our flats (#{@flats.count})" %> </h1>

<div class="container">
    <div class="row">
<% @flats.each do |flat| %>
  <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card shadow bg-white rounded">
        <div class="card-image" style="background-image: url('https://countrysidestays-japan.com/img/article/tsuru,kosuga/story_mv.jpg')"></div>
          <div class="card-body">
          <div class="card-content">
            <div class="card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.description %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons mr-2">people</i><span class="mr-2"><%= flat.number_of_guests %></span>
                 <i class="material-icons mr-2">euro_symbol</i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="card-actions">
            <%= link_to 'More info', flat_path(flat), class: 'ml-3' %> 
            <%= link_to 'Edit', flat_path(flat), class: 'text-warning ml-2' %>
            <%= link_to 'Delete', flat_path(flat), class: 'text-danger ml-2', method: :delete %>
          </div>
          </div>
        </div>
    </div>
  <% end %>
</div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for (@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add Flat"%>
<% end %>

app/views/flats/show.html.erb
<h1>flat info</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>